export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_SHIPPING = "UPDATE_SHIPPING";
export const UPDATE_PAYMENT = "UPDATE_PAYMENT";
export const FETCH_PRODUCTS_BEGIN   = 'FETCH_PRODUCTS_BEGIN';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const SUBMIT_ORDER_BEGIN   = 'SUBMIT_ORDER_BEGIN';
export const SUBMIT_ORDER_SUCCESS = 'SUBMIT_ORDER_SUCCESS';
export const SUBMIT_ORDER_FAILURE = 'SUBMIT_ORDER_FAILURE';

